ipaxi/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

from ixbr_api.api.urls import v1router
title = 'IX.br API'


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('ixbr_api.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Your stuff: custom urls includes go here
    url(r'^api/v1/', include((v1router.urls), namespace='api')),
    url(r'^core/', include('ixbr_api.core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

ipaxi/ixbr_api/api/urls.py
from .api_views import (BilateralViewSet, IXViewSet)
from ixbr_api.core.utils.regex import Regex
from rest_framework.routers import DefaultRouter

v1router = DefaultRouter()
regex = Regex()

v1router.register(r'ix', IXViewSet, 'ix')
v1router.register(r'ix/(?P<code>' + regex.ix_code + ')/asn/(?P<asn>' +
                  regex.number + ')/bilaterals', BilateralViewSet,
                  'bilateral')

ipaxi/ixbr_api/core/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .utils.regex import Regex
from .views import (as_views, core_views, form_views, function_based_views,
                    ip_views, ix_views, nikiti_views, switch_views, tag_views)

app_name = 'core'
regex = Regex()

as_urls = [
    url(
        regex=r'^as/(?P<asn>' + regex.number + ')/$',
        view=as_views.ASDetailView.as_view(),
        name='as_detail'
    ),
    url(
        regex=r'^as/search/',
        view=as_views.ASSearchView.as_view(),
        name='as_search'
    ),
    url(
        regex=r'^as/(?P<asn>' + regex.number + ')/whois/$',
        view=as_views.ASWhoisView.as_view(),
        name='as_whois'
    ),
    url(
        regex=r'^ix/(?P<code>' + regex.ix_code + ')/'
        '(?P<asn>' + regex.number + ')/$',
        view=as_views.ASIXDetailView.as_view(),
        name='ix_as_detail'
    ),
]

core_urls = [
    url(
        regex=r'^ix/(?P<code>' + regex.ix_code + ')/bundle/$',
        view=core_views.BundleEtherListView.as_view(),
        name='bundle_list'
    ),
    url(
        regex=r'^(?:home)?/?$',
        view=core_views.HomeView.as_view(),
        name='home'
    ),
    url(
        regex=r'^name/search/',
        view=core_views.SearchASNByNameView.as_view(),
        name='name_search'
    ),
    url(
        regex=r'^uuid/search/',
        view=core_views.SearchUUIDView.as_view(),
        name='uuid_search'
    ),
]

forms_urls = [
    url(
        regex=r'^form/add-contact/(?P<asn>' + regex.number + ')/$',
        view=form_views.AddASContactFormView.as_view(),
        name='add_as_contact_form'
    ),
    url(
        regex=r'^form/add-customer-channel/(?P<asn>' + regex.number +
        ')/(?P<pix>' + regex.uuid + ')/$',
        view=form_views.AddCustomerChannelFormView.as_view(),
        name='add_customer_channel_form'
    ),
    url(
        regex=r'^form/add-bilateral/(?P<asn>' + regex.number +
        ')/(?P<channel>' + regex.uuid + ')/$',
        view=form_views.AddBilateralFormView.as_view(),
        name='add_bilateral_form'
    ),
    url(
        regex=r'^form/add-contact/(?P<contactsmap>' + regex.uuid + ')/$',
        view=form_views.AddContactFormView.as_view(),
        name='add_contact_form'
    ),
    url(
        regex=r'^form/add-dio/(?P<pix>' + regex.uuid + ')/$',
        view=form_views.AddDIOToPIXFormView.as_view(),
        name='add_dio_form'
    ),
    url(
        regex=r'^form/add-ix-to-asn/(?P<asn>' + regex.number + ')/$',
        view=form_views.AddIXtoASNFormView.as_view(),
        name='add_ix_to_asn_form'
    ),
    url(
        regex=r'^form/add-phone/(?P<contact>' + regex.uuid + ')/$',
        view=form_views.AddPhoneFormView.as_view(),
        name='add_phone_form'
    ),
    url(
        regex=r'^form/create-ix/$',
        view=form_views.CreateIXFormView.as_view(),
        name='create_ix_form'
    ),
    url(
        regex=r'^form/edit-contact/(?P<contact>' + regex.uuid +
        ')/(?P<contactsmap>' + regex.uuid + ')/(?P<type_contact>' +
        regex.type + ')/$',
        view=form_views.EditContactFormView.as_view(),
        name='edit_contact_form'
    ),
    url(
        regex=r'^form/edit-contacts-map/(?P<contactsmap>' + regex.uuid +
        ')/(?P<ix>' + regex.ix_code + ')/(?P<asn>' + regex.number + ')/$',
        view=form_views.EditContactsMapFormView.as_view(),
        name='edit_contacts_map_form'
    ),
    url(
        regex=r'^form/create-organization/$',
        view=form_views.CreateOrganizationFormView.as_view(),
        name='create_organization_form'
    ),
    url(
        regex=r'^form/create-port-physical-interface/$',
        view=form_views.CreatePortPhysicalInterfaceFormView.as_view(),
        name='create_port_physical_interface_form'
    ),
    url(
        regex=r'^form/migrate-switch/(?P<pix>' + regex.uuid + ')/$',
        view=form_views.MigrateSwitchFormView.as_view(),
        name='migrate_switch_form'
    ),
    url(
        regex=r'^form/edit-dio-port/(?P<pix>' + regex.uuid +
        ')/(?P<dio_port>' + regex.uuid + ')/$',
        view=form_views.EditDioPortFormView.as_view(),
        name='edit_dio_port_form'
    ),
    url(
        regex=r'^form/edit_description_by_port/(?P<port>' + regex.uuid +
        ')/$',
        view=form_views.EditDescriptionByPortFormView.as_view(),
        name='edit_description_by_port_form'
    ),
    url(
        regex=r'^form/edit-tag-description/(?P<tag>' + regex.uuid +
        ')/$',
        view=form_views.EditTagDescriptionFormView.as_view(),
        name='edit_tag_description_form'
    ),
    url(
        regex=r'^form/edit-ip-description/(?P<ipv4>' + regex.ipv4 +
        ')/(?P<ipv6>' + regex.ipv6 + ')/$',
        view=form_views.EditIPDescriptionFormView.as_view(),
        name='edit_ip_description_form'
    ),
    url(
        regex=r'^form/edit-cix-type/(?P<channel>' + regex.uuid + ')/$',
        view=form_views.EditCixTypeFormView.as_view(),
        name='edit_cix_type_form'
    ),
    url(
        regex=r'^form/phone-edit/(?P<phone>' + regex.uuid + ')/$',
        view=form_views.EditPhoneFormView.as_view(),
        name='edit_phone_form'
    ),
    url(
        regex=r'^form/add-port-channel/(?P<pix>' + regex.uuid +
        ')/(?P<channel>' + regex.uuid + ')/$',
        view=form_views.AddPortChannelFormView.as_view(),
        name='add_port_channel_form'
    ),
    url(
        regex=r'^form/edit-port-interface-physical/(?P<port>' + regex.uuid +
        ')/$',
        view=form_views.EditPortPhysicalInterfaceFormView.as_view(),
        name='edit_port_physical_interface_form'
    ),
    url(
        regex=r'^form/edit-port-configured-capacity/(?P<port>' +
        regex.uuid + ')/$',
        view=form_views.EditConfiguredCapacityPortFormView.as_view(),
        name='edit_port_configured_capacity_form'
    ),
    url(
        regex=r'^form/generic-mlpa-add/(?P<asn>' + regex.number +
        ')/(?P<channel>' + regex.uuid + ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.GenericMLPAUsedChannelFormView.as_view(),
        name='generic_mlpa_add_form'
    ),
    url(
        regex=r'^form/generic-new-mlpa-add/(?P<asn>' + regex.number +
        ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.GenericMLPANewChannelFormView.as_view(),
        name='generic_new_mlpa_add_form'
    ),
    url(
        regex=r'^form/new-bilateral-used-channel/(?P<asn>' + regex.number +
        ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.AddBilateralNewChannelFormView.as_view(),
        name='new_bilateral_used_channel'
    ),
    url(
        regex=r'^form/add-mac-service/(?P<service>' + regex.uuid + ')/$',
        view=form_views.AddMACServiceFormView.as_view(),
        name='add_mac_service_form'
    ),
    url(
        regex=r'^form/tag/allocate-status/(?P<ix>' + regex.ix_code +
              ')/$',
        view=form_views.AllocateTagStatusFormView.as_view(),
        name='allocate_tag_status'
    ),
    url(
        regex=r'^form/tag/deallocate-status/(?P<ix>' + regex.ix_code +
              ')/$',
        view=form_views.DeallocateTagStatusFormView.as_view(),
        name='deallocate_tag_status'
    ),
    url(
        regex=r'^form/edit-mlpav4/(?P<service>' + regex.uuid +
        ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.EditMLPAv4FormView.as_view(),
        name='edit_mlpav4_form'
    ),
    url(
        regex=r'^form/edit-mlpav6/(?P<service>' + regex.uuid +
        ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.EditMLPAv6FormView.as_view(),
        name='edit_mlpav6_form'
    ),
    url(
        regex=r'^form/modal-feedback/$',
        view=form_views.EditContactFormView.as_view(),
        name='modal_feedback'
    ),
    url(
        regex=r'^form/edit-organization/(?P<organization>' + regex.uuid +
        ')/$',
        view=form_views.EditOrganizationFormView.as_view(),
        name='edit_organization_form'
    ),
    url(
        regex=r'^form/add-pix-to-asn/(?P<ix>' + regex.ix_code +
        ')/(?P<asn>' + regex.number + ')/$',
        view=form_views.AddPixToAsnFormView.as_view(),
        name='add_pix_to_asn_form'
    ),
    url(
        regex=r'^form/edit-service-status/(?P<service>' + regex.uuid + ')/$',
        view=form_views.EditServiceStatusFormView.as_view(),
        name='edit_service_status_form'
    ),
    url(
        regex=r'^form/service-prefix-limit-edit/(?P<service>' + regex.uuid +
        ')/$',
        view=form_views.EditServicePrefixLimitFormView.as_view(),
        name='edit_service_prefix_limit_form'
    ),
    url(
        regex=r'^form/edit-service-tag/(?P<service>' + regex.uuid +
        ')/(?P<code>' + regex.ix_code + ')/$',
        view=form_views.EditServiceTagFormView.as_view(),
        name='edit_service_tag_form'
    ),
    url(
        regex=r'^form/ip/resource-reserve/(?P<ix>' + regex.ix_code + ')/$',
        view=form_views.ReserveIPResourceFormView.as_view(),
        name='reserve_ip_resource'
    ),
    url(
        regex=r'^form/ip/resource-release/(?P<ix>' + regex.ix_code + ')/$',
        view=form_views.ReleaseIPResourceFormView.as_view(),
        name='release_ip_resource'
    ),
    url(
        regex=r'^form/port/resource-reserve/(?P<sw>' + regex.uuid +
              ')/$',
        view=form_views.ReservePortResourceFormView.as_view(),
        name='reserve_port_resource'
    ),
    url(
        regex=r'^form/port/resource-release/(?P<sw>' + regex.uuid + ')/$',
        view=form_views.ReleasePortResourceFormView.as_view(),
        name='release_port_resource'
    ),
    url(
        regex=r'^form/port/add-switch-module/(?P<switch>' + regex.uuid + ')/$',
        view=form_views.AddNewSwitchModuleFormView.as_view(),
        name='add_switch_module'
    ),
    url(
        regex=r'^form/tag/resource-reserve/(?P<ix>' + regex.ix_code +
              ')/$',
        view=form_views.ReserveTagResourceFormView.as_view(),
        name='reserve_tag_resource'
    ),
    url(

ipaxi/ixbr_api/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

ipaxi/ixbr_api/core/views/ip_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.views.generic import View

from ..models import IX, IPv4Address, IPv6Address, MLPAv4, MLPAv6, Monitorv4


class IPListView(LoginRequiredMixin, View):
    """List IPs of a specific location.

    List ips into a table marked by ALLOCATED or FREE status.
    And show stats of IPs.

    Attributes:
        context (dict): Dictionary that return a set of informations
            to be printed.
        dict_ips (dict): Dictionary with IP address and its status
            (ALLOCATED or FREE).
        allocated_ipv4 (QuerySet): cached information of allocated ip v4
        allocated_ipv6 (QuerySet): cached information of allocated ip v6
        ipv4s (<class 'django.db.models.query.QuerySet'>): Get queryset with
            filtered IPv4s from a specified IX.
        ipv6s (<class 'django.db.models.query.QuerySet'>): Get queryset with
            filtered IPv6s from a specified IX.
        ix (<class 'ixbr_api.core.models.IX'>): Get the ix from IX models or
            return a 404.
        template_name (str): core/ip_list.html'

    Returns:
        A dict context with all information about a collection of IPs into a
        IX. For example:
        {
          'ix': <IX: [jpa]>,
          'ips': {
            1: {
              'v4': <IPv4Address: [187.16.193.1]>,
              'v4_status': "ALLOCATED"
              'v6': <IPv6Address: [2001:12f8:0:16::1]>
              'v6_status': "ALLOCATED"
            },
            2: {
              'v4': <IPv4Address: [187.16.193.2]>,
              'v4_status': "FREE"
              'v6': <IPv6Address: [2001:12f8:0:16::2]>
              'v6_status': "FREE"
            },
            3: {
              'v4': <IPv4Address: [187.16.193.3]>,
              'v4_status': "FREE"
              'v6': <IPv6Address: [2001:12f8:0:16::3]>
              'v6_status': "FREE"
            }
          }
        }
    """

    def get(self, request, code):
        template_name = 'core/ip_list.html'
        ix = get_object_or_404(IX, code=code)
        ipv4s = IPv4Address.objects.filter(ix=code)
        ipv6s = IPv6Address.objects.filter(ix=code)

        allocated_ipv4 = IPv4Address.objects.filter(
            Q(address__in=MLPAv4.objects.filter(
                mlpav4_address__ix=code).values_list(
                'mlpav4_address', flat=True))
            | Q(address__in=Monitorv4.objects.filter(
                monitor_address__ix=code).values_list(
                'monitor_address', flat=True)))

        allocated_ipv6 = IPv6Address.objects.filter(
            Q(address__in=MLPAv6.objects.filter(
                mlpav6_address__ix=code).values_list(
                'mlpav6_address', flat=True)))

        dict_ips = dict()
        for index, ipv4 in enumerate(ipv4s):
            # index+1 because IPs start at 1
            dict_ips[index+1] = {
                "v4": ipv4,
                "v4_status": "ALLOCATED" if ipv4 in allocated_ipv4 else "FREE",
                "v6": ipv6s[index],
                "v6_status": "ALLOCATED" if ipv6s[index] in allocated_ipv6
                             else "FREE"
            }

        context = {'ips': dict_ips, 'ix': ix}
        return render(request, template_name, context)

ipaxi/ixbr_api/core/views/switch_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views.generic import View

from ..models import IX, Switch, SwitchModule


class SwitchListView(LoginRequiredMixin, View):
    """List the summary of a switch

    Attributes:
        ix (<class 'ixbr_api.core.models.IX'>): Get the ix from IX models or
            return a 404.
        switch (<class 'django.db.models.query.QuerySet'>): Get queryset of a
            given switch.
    returns:
        A dict context with a Switch object and IX object specified.
    """

    def get(self, request, *args, **kwargs):
        template_name = 'core/switch_detail.html'

        ix_code = kwargs['code']
        switch_uuid = kwargs['switch_uuid']

        self.ix = get_object_or_404(IX, code=ix_code)
        self.switch = Switch.objects.get(pk=switch_uuid)

        context = {
            'ix': self.ix,
            'switch': self.switch,
            }
        return render(request, template_name, context)

class SwitchModuleDetailView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        template_name = 'core/switch_module_detail.html'

        module_id = kwargs['module']

        self.switch_module = get_object_or_404(SwitchModule, pk=module_id)

        context = {
            'module': self.switch_module
        }

        return render(request, template_name, context)

ipaxi/ixbr_api/templates/core/bundle_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}IX: {{ix.code}} | Bundle-Ethers{% endblock %}

{% block content %}
<div class="container">
	<h1>PIXs of {{ ix.fullname }} </h1>
	<table id="bundle" class="table table-striped table-resposive" width="100%">
		<thead class="thead-inverse">
			<tr>
				<th>Bundle-ethers list</th>
			</tr>
		</thead>
		<tbody>
			{% for bundle in object_list %}
				<tr>
					<td><a href="{% url 'core:tag_list_with_bundle' code=ix.code bundle_pk=bundle.uuid %}">TAGs from bundle {{ bundle.name }}</a> | {% for switch in bundle.get_switches%}<a href="{% url 'core:switch_detail' code=ix.code switch_uuid=switch.uuid %}"> Switch: {{ switch.management_ip }}  {{ switch.model}}{% endfor %}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% endblock content %}

ipaxi/ixbr_api/templates/core/ip_list.html
{% extends 'base.html' %}
{% load static %}
{% load core_filters %}

{% block title %}IX: {{ ix.fullname }} | Allocation IPs{% endblock %}
{% block content %}
    <div id="input-warning" class="alert alert-warning hidden">
    	<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
    	<strong>Warning!</strong> This ASN doesn't match with this ip.
    </div>
    <div id="input-error" class="alert alert-danger hidden">
    	<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
    	<strong>Error!</strong> Please, insert a not empty input.
    </div>
    <div class="container">
    	<input type="hidden" value="">
    	<div class="row">
    		<div class="title-container">
                <div>
        			<h1 class="title-header">IPs Allocation at</h1>
        		</div>
        		<div>
        			<h1 class="title-header"><span>{{ ix.fullname }}</span></h1>
        		</div>
            </div>
    	</div>
        <br>
        <br>
    	<div class="row">
    		<div class="col-lg-6 col-md-6 search-asn-by-ips">
    			<div class="input-group">
    				<input type="number" min="1" max="2147483647" class="form-control" name="asn" id="asn" placeholder="Search IP by ASN...">
    				<span class="input-group-btn">
    					<button class="btn btn-primary" id="pesquisar-asn-ips">Search</button>
    				</span>
    			</div>
    		</div>
    		<div class="col-md-6" align="right">
    			<select name="filter_ips" class="custom-select" id="filter_ips">
    				<option value="">Filter IPs by status</option>
    				<option value="ALL">All IPs</option>
    				<option value="FREE" data-typeip="ipv4">IPv4 Free</option>
    				<option value="ALLOCATED" data-typeip="ipv4">IPv4 Allocated</option>
    				<option value="FREE" data-typeip="ipv6">IPv6 Free</option>
    				<option value="ALLOCATED" data-typeip="ipv6">IPv6 Allocated</option>
    			</select>
    		</div>
    	</div>
        <br>
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <a href="{% url 'core:reserve_ip_resource' ix=ix.code %}" data-toggle="modal" data-target="#modal">Reserve IP</a>
            </div>
            <div class="col-lg-12 col-md-12">
                <a href="{% url 'core:release_ip_resource' ix=ix.code %}" data-toggle="modal" data-target="#modal">Release IP</a>
            </div>
        </div>
        <br>
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
    	<table id="ip-list-table" class="table table-striped borderless table-resposive" width="100%">
    	<thead class="thead-inverse">
    		<tr>
    			<th class="text-center">IPv4</th>
    			<th class="text-center">Status</th>
        		<th class="text-center">Reserved</th>
    			<th class="text-center">IPv6</th>
    			<th class="text-center">Status</th>
        		<th class="text-center">Reserved</th>
                <th class="text-center">Description</th>
    		</tr>
    	</thead>
    	<tbody>
    		{% for key, value in ips.items %}
    			<tr class="basic-ip-info-detail" id="border-{{key}}" data-open="{{key}}" data-ip='{{value.v4.address}}' data-ipv='{{value.v6.address}}'>
    				<td class="text-center">{{value.v4.address}}</td>
    				{% if value.v4_status == 'FREE' %}
    				<td class="text-center text-success status-ipv4" data-open="{{key}}">{{value.v4_status}}</td>
    				{% endif %}
    				{% if value.v4_status == 'ALLOCATED' %}
    				<td class="text-center text-danger status-ipv4" data-open="{{key}}">{{value.v4_status}}</td>
    				{% endif %}
    				<td class="text-center text-danger status-ipv4" data-open="{{key}}">{% if value.v4.is_reserved%}{{value.v4.is_reserved}}{% endif %}</td>
    				<td class="text-center">{{value.v6.address}}</td>
    				{% if value.v6_status == 'FREE' %}
    				<td class="text-center text-success status-ipv6" data-open="{{key}}">{{value.v6_status}}</td>
    				{% endif %}
    				{% if value.v6_status == 'ALLOCATED' %}
    				<td class="text-center text-danger status-ipv6" data-open="{{key}}">{{value.v6_status}}</td>
    				{% endif %}
    				<td class="text-center text-danger status-ipv6" data-open="{{key}}">{% if value.v6.is_reserved%}{{value.v6.is_reserved}}{% endif %}</td>
                    <td class="align-middle text-center status-ipv4" data-open="{{key}}">
                        <div class="">
                            {{ value.v4.description }}
                        </div>
                        <div class="">
                            {% if value.v4.description == "" %}
                                <i class="fa fa-plus-circle no_display" aria-hidden="true" href="{% url 'core:edit_ip_description_form' ipv4=value.v4.pk ipv6=value.v6.pk %}" data-toggle="modal" data-target="#modal" title="Add description"></i>
                            {% else %}
                                <i class="fa fa-pencil-square-o no_display" aria-hidden="true" href="{% url 'core:edit_ip_description_form' ipv4=value.v4.pk ipv6=value.v6.pk %}" data-toggle="modal" data-target="#modal" title="Edit description"></i>
                            {% endif %}
                        </div>
                    </td>
    			</tr>
    			<tr class="more-ip-info-detail" id="detail-open-{{key}}">
    				<td colspan="3">
    					<div class="col-md-12 more-ip-detail text-center" id="ipv4-detail-{{key}}">
    						<p id="ipv4-detail-paragraph-asn-{{key}}" class="ip-detail-paragraph">ASN: <a href="{% url 'core:as_detail' asn=0 %}"><span id="ipv4-asn-{{key}}"></span></a></p>
    						<p id="ipv4-detail-paragraph-name-{{key}}" class="ip-detail-paragraph">NAME: <a href="{% url 'core:ix_as_detail' code=ix.code asn=0 %}"><span id="ipv4-name-{{key}}"></span></a></p>
    					</div>
    				</td>
    				<td colspan="4">
    					<div class="col-md-12 more-ip-detail text-center" id="ipv6-detail-{{key}}">
    						<p id="ipv6-detail-paragraph-asn-{{key}}" class="ip-detail-paragraph">ASN: <a href="{% url 'core:as_detail' asn=0 %}"><span id="ipv6-asn-{{key}}"></span></a></p>
    						<p id="ipv6-detail-paragraph-name-{{key}}" id= class="ip-detail-paragraph">NAME: <a href="{% url 'core:ix_as_detail' code=ix.code asn=0 %}"><span id="ipv6-name-{{key}}"></span></a></p>
    					</div>
    				</td>
                </tr>
    		{% endfor %}
    	</tbody>
    </table>

    <!-- Modal -->
    <div id="modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div id="asModalHeader" class="modal-header">
                    <div class="title-holder">
                        <h1>Loading IPs...</h1>
                    </div>
                    <button type="button" class="close pt-0" aria-label="Close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                 <div class="modal-body my-3">
                    <div class="d-flex flex-sm-column align-items-center">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
   {{ block.super }}
    <script type="text/javascript">
      var code = "{{ix.code}}";
    </script>
    <script src="{% static 'js/ip_list.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modal_render.js' %}"></script>
{% endblock %}


{#<a href="{% url 'core:add_phone_form' contact=organization_contacts.adm_contact.pk %}" data-toggle="modal" data-target="#modal">[add_phone]</a>#}